/*
 * GENERATED-EQUIVALENT — do not edit by hand.
 *
 * These types are the public-site view of the content model. They are canonical
 * in the API's Zod schemas (portfolio-v6-api/src/schemas/, spec §3.9) and are
 * meant to be regenerated by `npm run sync:types`, which fetches the API's
 * `GET /api/schema` (JSON Schema derived from those Zod definitions) and
 * overwrites this file (spec §8.4).
 *
 * Until that endpoint exists, this file is hand-derived *exactly* from spec
 * §3 to the same shape discipline as the other repos. When `sync:types` runs
 * for real it replaces the whole file — keep edits in the API schemas, not here.
 */

/* ---- Links (spec §3.4) ---------------------------------------------------- */

/**
 * A single outbound link. Replaces v5's `url` / `repo` scalars so a project can
 * span several repos, dev + prod deployments, docs, etc. Reused by portfolio
 * items and by the blog's `links` block (§3.7).
 *
 * `label` is required and NOT derived from `type` — five `repo` links are
 * otherwise indistinguishable. `type` drives the icon/grouping; `label` says
 * which one. Array order is display order. Protocol is `http`/`https` only,
 * enforced at the admin write boundary (§3.4).
 */
export type LinkType =
  | 'repo'
  | 'prod'
  | 'dev'
  | 'docs'
  | 'demo'
  | 'package'
  | 'article'
  | 'other';

export interface Link {
  type: LinkType;
  label: string;
  url: string;
}

/* ---- Section types (spec §3.4) -------------------------------------------- */

/**
 * `sections.type` — a string in the DB, a discriminated union here. The public
 * site's SECTION_REGISTRY is keyed by these (§3.4). An unknown `type` renders
 * nothing and logs, so a not-yet-deployed public site degrades rather than
 * crashes.
 */
export type SectionType =
  | 'hero'
  | 'about'
  | 'timeline'
  | 'skills'
  | 'portfolio'
  | 'status'
  | 'blog'
  | 'now_playing'
  | 'duolingo'
  | 'github'
  | 'ops'
  | 'resume'
  | 'contact';

/* ---- Section item shapes (spec §3.4 item table) --------------------------- */

/** `timeline` item. */
export interface TimelineItem {
  date_range: string;
  title: string;
  description: string;
  media_id?: string;
}

/**
 * `skills` item (spec §3.4, v1.5). The v5 skill rating was removed in v1.5 — the
 * public renderer is now a geodesic sphere of icons, not per-skill meters.
 */
export interface SkillsItem {
  title: string;
  description: string;
  /** Default (light-theme) icon URL — required. Source-agnostic plain URL. */
  icon_source: string;
  /**
   * Optional dark-theme icon override (Icons v1.6). A plain URL like
   * {@link icon_source}; every renderer falls back to `icon_source` when it is
   * absent. Lets a skill ship a dark-optimised glyph (e.g. a white wordmark)
   * without changing the light-theme icon.
   */
  icon_source_dark?: string;
}

/** `portfolio` item. */
export interface PortfolioItem {
  title: string;
  intro: string;
  description: string;
  media_id: string;
  playback_rate?: number;
  transform_value?: string;
  /**
   * Ordered skills-item ids this project references (Skill Refs v1.8) — items of
   * `skills`-type sections on ANY page of the same published document. Array
   * order is render order; empty is allowed. The portfolio renders each
   * referenced skill's THEME-AWARE icon and title, so portfolio marks and the
   * skills sphere can never show mismatched icons — icon consistency is enforced
   * by construction (publish guarantees every entry resolves; the renderer still
   * skips an unresolvable ref defensively). Replaces v5's bare `tech_icons` URL
   * array (§3.4).
   */
  skill_refs: string[];
  /**
   * LEGACY (pre-v1.8): a bare array of tech-icon URLs with no theme awareness or
   * companion labels. Documents published before Skill Refs v1.8 carry this
   * instead of {@link skill_refs} and keep rendering exactly as before until Ben
   * republishes; v1.8 documents omit it. Not part of the canonical API schema —
   * a render-time fallback only (§3.4).
   */
  tech_icons?: string[];
  links: Link[];
  /**
   * Related published posts (Post Refs v1.14). The API resolves these
   * server-side to currently-published posts only, in the author's order, and
   * serializes them on each portfolio item in `GET /api/content` (and the admin
   * preview). Draft/deleted refs never reach this payload, so the renderer needs
   * no filtering. Optional so a pre-v1.14 payload (or the not-yet-regenerated
   * local schema) degrades to "no related posts" rather than crashing — an
   * absent or empty array renders nothing.
   */
  posts?: PostRef[];
}

/**
 * A related-post reference on a portfolio item (Post Refs v1.14) — the minimal
 * shape needed to render an internal link to the post: its `id` (React key),
 * `slug` (routed to `/blog/<slug>`), display `title`, and owning {@link Blog}
 * identity (`null` when the post belongs to no blog). Already resolved to a
 * currently-published post server-side; the public site only ever renders it.
 */
export interface PostRef {
  id: string;
  slug: string;
  title: string;
  blog: Blog | null;
}

/* ---- Static-section config shapes (spec §3.4) ----------------------------- */

/**
 * The `hero` section's optional backdrop tuning (task 132). Every key is optional
 * and any invalid or unknown value falls back to the site's default at render.
 * Persisted inside the hero section's `data.background` jsonb blob and echoed
 * into the published document snapshot alongside `background_media_id`, so a
 * hero with only a media id keeps rendering exactly as it does today.
 *
 * Ranges enforced at both the API write boundary and the public renderer's
 * sanitiser (a bad snapshot can never inject CSS):
 * - `opacity_dark` / `opacity_light`: 0..1 (defaults 0.1 dark, 0.06 light)
 * - `object_fit`: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down' (default 'cover')
 * - `object_position`: short CSS position string, max 40 chars, letters/digits/
 *   spaces/`%`/`.`/`-` only (default '50% 50%')
 * - `blur_px`: 0..40 (default 0)
 * - `grayscale`: 0..1 (default 0)
 * - `brightness` / `contrast` / `saturate`: 0..2 (default 1)
 * - `scale`: 1..2 (default 1); lets a blurred image hide its soft edges
 * - `overlay_dark` / `overlay_light`: 0..1 (default 0); alpha of a
 *   `--ground`-coloured overlay per theme to soften the image without losing
 *   detail
 */
export interface HeroBackground {
  opacity_dark?: number;
  opacity_light?: number;
  object_fit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  object_position?: string;
  blur_px?: number;
  grayscale?: number;
  brightness?: number;
  contrast?: number;
  saturate?: number;
  scale?: number;
  overlay_dark?: number;
  overlay_light?: number;
}

/**
 * The `hero` section's published config (spec §3.4). Optional header copy plus
 * an optional {@link HeroBackground} tuning blob for the CMS backdrop image
 * referenced by `background_media_id` (task 132).
 */
export interface HeroSectionData {
  title?: string;
  tagline?: string;
  intro?: string;
  background_media_id?: string;
  background?: HeroBackground;
}

/**
 * The `skills` section's published config (spec §3.4, v1.5). Optional `heading` /
 * `intro` override the section header copy.
 *
 * `sphere_detail` is the three.js `IcosahedronGeometry` detail parameter for the
 * geodesic skill sphere — an integer 0–4, where the face count is
 * `20·(detail+1)²` (0→20, 1→80, 2→180, 3→320, 4→500). When absent/undefined the
 * renderer AUTO-fits: it picks the smallest detail whose face count covers the
 * number of skill items (clamped to 4).
 */
export interface SkillsSectionData {
  heading?: string;
  intro?: string;
  sphere_detail?: number;
}

/* ---- Live-section config shapes (spec §3.5) ------------------------------- */

/**
 * The `duolingo` section's published config (spec §3.5, v1.2). The section's
 * *config* is snapshotted; its *data* (streak, course progress) is fetched at
 * runtime from `GET /api/duolingo?language=<language>`.
 *
 * `language` is the Duolingo course code selecting which course to read from the
 * payload (default `es` — Spanish). `score_label` is a hand-maintained string
 * for the official in-app "Duolingo Score", which that endpoint does not expose
 * — the renderer shows it as a `TagChip`, visually distinct from the live mono
 * values (spec §3.5). Optional `heading` / `eyebrow` / `intro` override the
 * section header copy.
 */
export interface DuolingoSectionData {
  heading?: string;
  eyebrow?: string;
  intro?: string;
  language?: string;
  score_label?: string;
}

/**
 * The `github` section's published config (spec §3.5, v1.10). The section's
 * *config* is snapshotted; its *data* (the browsable contribution calendar) is
 * fetched at runtime from `GET /api/github` (default trailing 12 months) and
 * `GET /api/github?year=YYYY` (a chosen calendar year).
 *
 * As of v1.10 the calendar spans a full year with an in-section year picker, so
 * the v1.2 `weeks` count is gone from the schema; older published documents may
 * still carry it and the renderer simply ignores it. Only the header copy
 * (`heading` / `eyebrow` / `intro`) is snapshotted.
 */
export interface GithubSectionData {
  heading?: string;
  eyebrow?: string;
  intro?: string;
}

/**
 * The `ops` section's published config (spec §3.5, DESIGN.md §5, v1.7). The
 * section's *config* is snapshotted; its *data* is the immutable daily ops report
 * fetched at runtime from `GET /api/ops` and replayed client-side.
 *
 * As of the v1.7 replay rework the lookback is no longer configurable — a report
 * always covers one full UTC day — so `window_hours` is removed; only the header
 * copy (`heading` / `intro`) is snapshotted.
 */
export interface OpsSectionData {
  heading?: string;
  eyebrow?: string;
  intro?: string;
}

/**
 * The `resume` section's published config (spec §3.5). The section's *config* is
 * snapshotted (optional header copy only); its *data* — the newest uploaded PDF —
 * is fetched at runtime from `GET /api/resume` so a new upload appears without a
 * content republish. There are no items and no other configurable knobs: the
 * viewer always shows the latest PDF.
 */
export interface ResumeSectionData {
  heading?: string;
  eyebrow?: string;
  intro?: string;
}

/**
 * The `data` blob of a repeatable child. Section types without repeatable
 * content (hero, about, status, blog, now_playing, duolingo, github, ops,
 * resume, contact) have zero items.
 */
export type SectionItemData = TimelineItem | SkillsItem | PortfolioItem;

export interface SectionItem {
  id: string;
  data: SectionItemData;
}

/**
 * A section as it appears in the published document served by `GET /api/content`
 * (§4.1). `data` is the section's own config blob; `items` are its repeatable
 * children (empty for non-repeatable / live sections).
 */
export interface Section {
  id: string;
  type: SectionType;
  data: Record<string, unknown>;
  items: SectionItem[];
}

/* ---- Pages & the published document (spec §3.10, §4.1) -------------------- */

/**
 * A first-class page in the published document (v1.1, spec §3.10). The admin
 * composes any number of pages from the section palette; the public site renders
 * whichever pages the document carries.
 *
 * `slug` is the URL segment (lowercase `[a-z0-9-]+`, unique). The slug `home`
 * renders at `/`; every other page renders at `/<slug>`. `title` drives the page
 * heading / document `<title>`. `nav_label` is the label shown in the site nav —
 * `null` means the page is reachable by direct link but not listed in the nav.
 * `nav_position` orders the nav. Hidden pages are validated at publish and never
 * serialized, so every page here is a public page. `sections` are the page's
 * sections in display order (each mapped through `SECTION_REGISTRY`, §3.4).
 */
export interface PageDocumentPage {
  id: string;
  slug: string;
  title: string;
  nav_label: string | null;
  nav_position: number;
  sections: Section[];
}

/**
 * Shape of `GET /api/content` (v1.1 pages shape, spec §3.10, §4.1). If no version
 * has ever been published the API returns 200 with an empty `pages` array (never
 * a 404) — the public site renders an empty page, not an error (§4.1).
 */
export interface ContentDocument {
  version: number;
  published_at: string | null;
  pages: PageDocumentPage[];
  /**
   * `media_id` → resolved CDN reference for every asset referenced by the
   * document (§6.8). Optional so an older API payload without it degrades to
   * "no media" rather than crashing; the public site defaults it to `{}`.
   */
  media?: MediaMap;
}

/* ---- Blog block model (spec §3.7) ----------------------------------------- */

/**
 * A post body is an ordered array of blocks — a discriminated union on `type`,
 * mirroring the section registry so the same render/validate approach applies
 * one level down. The public site's BLOCK_REGISTRY is keyed by `type`; unknown
 * block types render nothing rather than crashing (§3.7).
 *
 * Inline text in `paragraph`, `list`, and `quote` is a constrained markdown
 * subset (bold, italic, inline code, links). Raw HTML is never stored or
 * rendered (§3.7).
 */
export type Block =
  | { type: 'heading'; level: 2 | 3 | 4; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; language: string; code: string; filename?: string }
  | { type: 'media'; media_id: string; caption?: string }
  | { type: 'list'; ordered: boolean; items: string[] }
  | { type: 'quote'; text: string; attribution?: string }
  | { type: 'links'; links: Link[] }
  | { type: 'divider' };

export type BlockType = Block['type'];

/* ---- Blog posts (spec §3.6, §4.1) ----------------------------------------- */

/**
 * A resolved media reference. `media_assets` stores `s3_key` only; the API
 * resolves keys to absolute CDN URLs at read time (§6.8), so the public site
 * only ever sees an absolute URL plus its `alt`.
 */
export interface MediaRef {
  url: string;
  alt: string | null;
}

/**
 * The published document's media lookup map: `media_id` → resolved reference
 * (§6.8). `media_assets` stores `s3_key` only; the content endpoint resolves
 * keys to absolute CDN URLs at read time, so sections reference media by id and
 * the public site looks the id up here to get a ready-to-render URL + `alt`.
 */
export type MediaMap = Record<string, MediaRef>;

/**
 * A post's blog identity (Blogs v1.13): the owning blog's `slug` (used to filter
 * the index, `/blog?blog=<slug>`) and its display `name`. A post that belongs to
 * no blog carries `blog: null`.
 */
export interface Blog {
  slug: string;
  name: string;
}

/**
 * `GET /api/posts` returns summaries only — never bodies (§4.1).
 */
export interface PostSummary {
  slug: string;
  title: string;
  excerpt: string;
  cover: MediaRef | null;
  tags: string[];
  published_at: string;
  /** The blog this post belongs to (Blogs v1.13), or `null` if none. */
  blog: Blog | null;
}

/**
 * `GET /api/posts/:slug` returns one published post, `published_body` only,
 * as a resolved `Block[]` (§4.1). 404 for a slug that exists but was never
 * published.
 */
export interface Post extends PostSummary {
  body: Block[];
  /**
   * `media_id` → resolved CDN reference for every asset referenced by this
   * post's body (§6.8) — the per-post analogue of {@link ContentDocument.media}.
   * A `media` block (§3.7) looks its `media_id` up here to get a ready-to-render
   * URL + `alt`. Optional so an older payload without it degrades to "no media"
   * rather than crashing; the public site defaults it to `{}`.
   */
  media?: MediaMap;
}
