/*
 * GENERATED-EQUIVALENT — do not edit by hand.
 *
 * These types are the public-site view of the content model. They are canonical
 * in the API's Zod schemas (portfolio-v6-api/src/schemas/, spec §3.9) and are
 * meant to be regenerated by `npm run sync:types`, which fetches the API's
 * `GET /api/schema` (JSON Schema derived from those Zod definitions) and
 * overwrites this file (spec §8.4).
 *
 * Until that endpoint exists, this file is hand-derived *exactly* from spec
 * §3 to the same shape discipline as the other repos. When `sync:types` runs
 * for real it replaces the whole file — keep edits in the API schemas, not here.
 */

/* ---- Links (spec §3.4) ---------------------------------------------------- */

/**
 * A single outbound link. Replaces v5's `url` / `repo` scalars so a project can
 * span several repos, dev + prod deployments, docs, etc. Reused by portfolio
 * items and by the blog's `links` block (§3.7).
 *
 * `label` is required and NOT derived from `type` — five `repo` links are
 * otherwise indistinguishable. `type` drives the icon/grouping; `label` says
 * which one. Array order is display order. Protocol is `http`/`https` only,
 * enforced at the admin write boundary (§3.4).
 */
export type LinkType =
  | 'repo'
  | 'prod'
  | 'dev'
  | 'docs'
  | 'demo'
  | 'package'
  | 'article'
  | 'other';

export interface Link {
  type: LinkType;
  label: string;
  url: string;
}

/* ---- Section types (spec §3.4) -------------------------------------------- */

/**
 * `sections.type` — a string in the DB, a discriminated union here. The public
 * site's SECTION_REGISTRY is keyed by these (§3.4). An unknown `type` renders
 * nothing and logs, so a not-yet-deployed public site degrades rather than
 * crashes.
 */
export type SectionType =
  | 'hero'
  | 'about'
  | 'timeline'
  | 'skills'
  | 'portfolio'
  | 'status'
  | 'blog'
  | 'now_playing'
  | 'contact';

/* ---- Section item shapes (spec §3.4 item table) --------------------------- */

/** `timeline` item. */
export interface TimelineItem {
  date_range: string;
  title: string;
  description: string;
  media_id?: string;
}

/** `skills` item. */
export interface SkillsItem {
  title: string;
  description: string;
  icon_source: string;
  proficiency: number;
}

/** `portfolio` item. */
export interface PortfolioItem {
  title: string;
  intro: string;
  description: string;
  media_id: string;
  playback_rate?: number;
  transform_value?: string;
  tech_icons: string[];
  links: Link[];
}

/**
 * The `data` blob of a repeatable child. Section types without repeatable
 * content (hero, about, status, blog, now_playing, contact) have zero items.
 */
export type SectionItemData = TimelineItem | SkillsItem | PortfolioItem;

export interface SectionItem {
  id: string;
  data: SectionItemData;
}

/**
 * A section as it appears in the published document served by `GET /api/content`
 * (§4.1). `data` is the section's own config blob; `items` are its repeatable
 * children (empty for non-repeatable / live sections).
 */
export interface Section {
  id: string;
  type: SectionType;
  data: Record<string, unknown>;
  items: SectionItem[];
}

/* ---- Pages & the published document (spec §3.10, §4.1) -------------------- */

/**
 * A first-class page in the published document (v1.1, spec §3.10). The admin
 * composes any number of pages from the section palette; the public site renders
 * whichever pages the document carries.
 *
 * `slug` is the URL segment (lowercase `[a-z0-9-]+`, unique). The slug `home`
 * renders at `/`; every other page renders at `/<slug>`. `title` drives the page
 * heading / document `<title>`. `nav_label` is the label shown in the site nav —
 * `null` means the page is reachable by direct link but not listed in the nav.
 * `nav_position` orders the nav. Hidden pages are validated at publish and never
 * serialized, so every page here is a public page. `sections` are the page's
 * sections in display order (each mapped through `SECTION_REGISTRY`, §3.4).
 */
export interface PageDocumentPage {
  id: string;
  slug: string;
  title: string;
  nav_label: string | null;
  nav_position: number;
  sections: Section[];
}

/**
 * Shape of `GET /api/content` (v1.1 pages shape, spec §3.10, §4.1). If no version
 * has ever been published the API returns 200 with an empty `pages` array (never
 * a 404) — the public site renders an empty page, not an error (§4.1).
 */
export interface ContentDocument {
  version: number;
  published_at: string | null;
  pages: PageDocumentPage[];
  /**
   * `media_id` → resolved CDN reference for every asset referenced by the
   * document (§6.8). Optional so an older API payload without it degrades to
   * "no media" rather than crashing; the public site defaults it to `{}`.
   */
  media?: MediaMap;
}

/* ---- Blog block model (spec §3.7) ----------------------------------------- */

/**
 * A post body is an ordered array of blocks — a discriminated union on `type`,
 * mirroring the section registry so the same render/validate approach applies
 * one level down. The public site's BLOCK_REGISTRY is keyed by `type`; unknown
 * block types render nothing rather than crashing (§3.7).
 *
 * Inline text in `paragraph`, `list`, and `quote` is a constrained markdown
 * subset (bold, italic, inline code, links). Raw HTML is never stored or
 * rendered (§3.7).
 */
export type Block =
  | { type: 'heading'; level: 2 | 3 | 4; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; language: string; code: string; filename?: string }
  | { type: 'media'; media_id: string; caption?: string }
  | { type: 'list'; ordered: boolean; items: string[] }
  | { type: 'quote'; text: string; attribution?: string }
  | { type: 'links'; links: Link[] }
  | { type: 'divider' };

export type BlockType = Block['type'];

/* ---- Blog posts (spec §3.6, §4.1) ----------------------------------------- */

/**
 * A resolved media reference. `media_assets` stores `s3_key` only; the API
 * resolves keys to absolute CDN URLs at read time (§6.8), so the public site
 * only ever sees an absolute URL plus its `alt`.
 */
export interface MediaRef {
  url: string;
  alt: string | null;
}

/**
 * The published document's media lookup map: `media_id` → resolved reference
 * (§6.8). `media_assets` stores `s3_key` only; the content endpoint resolves
 * keys to absolute CDN URLs at read time, so sections reference media by id and
 * the public site looks the id up here to get a ready-to-render URL + `alt`.
 */
export type MediaMap = Record<string, MediaRef>;

/**
 * `GET /api/posts` returns summaries only — never bodies (§4.1).
 */
export interface PostSummary {
  slug: string;
  title: string;
  excerpt: string;
  cover: MediaRef | null;
  tags: string[];
  published_at: string;
}

/**
 * `GET /api/posts/:slug` returns one published post, `published_body` only,
 * as a resolved `Block[]` (§4.1). 404 for a slug that exists but was never
 * published.
 */
export interface Post extends PostSummary {
  body: Block[];
  /**
   * `media_id` → resolved CDN reference for every asset referenced by this
   * post's body (§6.8) — the per-post analogue of {@link ContentDocument.media}.
   * A `media` block (§3.7) looks its `media_id` up here to get a ready-to-render
   * URL + `alt`. Optional so an older payload without it degrades to "no media"
   * rather than crashing; the public site defaults it to `{}`.
   */
  media?: MediaMap;
}
